package ai.julie.core.model.chatcompletion.create.message

import ai.julie.core.model.chatcompletion.create.message.content.MessageContentRequest
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AssistantMessageRequest(
    /**
     * The role of the messages author, in this case assistant.
     */
    @SerialName("role") override val role: String = "assistant",

    /**
     * Data about a previous audio response from the model.
     * [Learn more](https://platform.openai.com/docs/guides/audio).
     */
    @SerialName("audio") val audio: AssistantAudioRequest? = null,

    /**
     * The contents of the assistant message. Required unless tool_calls or function_call is
     * specified.
     */
    @SerialName("content") val content: MessageContentRequest? = null,

    // TODO: functioncall

    /**
     * An optional name for the participant. Provides the model information to differentiate between
     * participants of the same role.
     */
    @SerialName("name") override val name: String? = null,

    /**
     * The refusal message by the assistant.
     */
    @SerialName("refusal") val refusal: Boolean? = null,

    /**
     * The tool calls generated by the model, such as function calls.
     */
//  TODO:  @SerialName("tool_calls") val toolCalls: List<ToolCallRequest>? = null,
) : MessageRequest()

@Serializable
data class AssistantAudioRequest(
    /**
     * Unique identifier for a previous audio response from the model.
     */
    @SerialName("id") val id: String
)
